#!/usr/bin/env python3
"""Sync CLI help output into hand-written Reference pages."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Annotated

import typer

app = typer.Typer(add_completion=False)

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_GENERATED_DIR = REPO_ROOT / "docs" / "reference" / "cli" / "generated"
DEFAULT_CLI_DIR = REPO_ROOT / "docs" / "reference" / "cli"

MARK_START = "<!-- CLI-HELP-START -->"
MARK_END = "<!-- CLI-HELP-END -->"


@dataclass(frozen=True)
class DocSpec:
    command: str
    doc_basename: str


DOC_SPECS = [
    DocSpec("sc-preprocess-admittance", "convert-hfss-admittance"),
    DocSpec("sc-preprocess-phase", "convert-hfss-phase"),
    DocSpec("sc-convert-flux-dependence", "convert-flux-dependence"),
    DocSpec("sc-fit-squid", "squid-model-fit"),
    DocSpec("sc-simulate-lc", "sc-simulate-lc"),
    DocSpec("sc-db", "sc-db"),
]


def extract_help_text(path: Path) -> str:
    content = path.read_text(encoding="utf-8")
    fence = "```text"
    start = content.find(fence)
    if start == -1:
        raise ValueError(f"No text fence found in {path}")
    start = content.find("\n", start) + 1
    end = content.find("```", start)
    if end == -1:
        raise ValueError(f"No closing fence found in {path}")
    return content[start:end].strip("\n")


def build_block(help_text: str, lang: str) -> str:
    if lang == "en":
        heading = "## CLI Help (Auto-generated)"
        note = (
            "!!! note \"Auto-generated\"\n"
            "    This section is generated by `sc-docs-cli`. Do not edit manually."
        )
    else:
        heading = "## CLI Help（自動生成）"
        note = (
            "!!! note \"自動生成\"\n"
            "    此區塊由 `sc-docs-cli` 產生，請勿手動修改。"
        )

    return (
        f"{MARK_START}\n\n"
        f"{heading}\n\n"
        f"{note}\n\n"
        f"```text\n{help_text}\n```\n\n"
        f"{MARK_END}\n"
    )


def upsert_block(doc_path: Path, block: str, check_only: bool) -> bool:
    content = doc_path.read_text(encoding="utf-8")
    if MARK_START in content and MARK_END in content:
        before, rest = content.split(MARK_START, 1)
        _, after = rest.split(MARK_END, 1)
        new_content = before + block + after
    else:
        new_content = content.rstrip() + "\n\n" + block

    if check_only:
        normalized_existing = content.replace("\r\n", "\n").strip()
        normalized_new = new_content.replace("\r\n", "\n").strip()
        return normalized_existing == normalized_new

    if content != new_content:
        doc_path.write_text(new_content, encoding="utf-8")
    return True


@app.command()
def main(
    generated_dir: Annotated[
        Path,
        typer.Option(help="Directory containing generated CLI help pages"),
    ] = DEFAULT_GENERATED_DIR,
    cli_dir: Annotated[
        Path,
        typer.Option(help="Directory containing hand-written CLI reference pages"),
    ] = DEFAULT_CLI_DIR,
    check: Annotated[
        bool,
        typer.Option(help="Only check if docs are up to date"),
    ] = False,
) -> None:
    ok = True
    for spec in DOC_SPECS:
        for lang, suffix in (("zh", ""), ("en", ".en")):
            generated_path = generated_dir / f"{spec.command}{suffix}.md"
            doc_path = cli_dir / f"{spec.doc_basename}{suffix}.md"

            if not generated_path.exists():
                typer.echo(f"Missing generated: {generated_path}")
                ok = False
                continue
            if not doc_path.exists():
                typer.echo(f"Missing doc: {doc_path}")
                ok = False
                continue

            help_text = extract_help_text(generated_path)
            block = build_block(help_text, lang)
            if not upsert_block(doc_path, block, check_only=check):
                typer.echo(f"Out of date: {doc_path}")
                ok = False

    if check and not ok:
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
