"""Installable shared core boundary for backend, CLI, and future adopters."""

from sc_core.circuit_definitions import (
    DEFAULT_PREVIEW_ARTIFACTS,
    CircuitDefinitionInspection,
    ValidationLevel,
    ValidationNotice,
    inspect_circuit_definition_source,
)
from sc_core.execution import (
    EXECUTION_CONTRACT_VERSION,
    WORKER_TASK_FAILED_ERROR_CODE,
    ExecutionPhase,
    TaskAuditActionKind,
    TaskExecutionResult,
    TaskResultHandle,
    WorkerExecutionProvenance,
    audit_action_for_phase,
    build_task_crash_payload,
    build_task_failure_payload,
    build_task_start_payload,
    build_task_success_payload,
    build_worker_audit_summary,
)
from sc_core.tasking import (
    LaneName,
    TaskExecutionMode,
    TaskSubmissionKind,
    WorkerTaskName,
    WorkerTaskRoute,
    extract_parameters_payload,
    resolve_worker_task_route,
)

__all__ = [
    "DEFAULT_PREVIEW_ARTIFACTS",
    "EXECUTION_CONTRACT_VERSION",
    "WORKER_TASK_FAILED_ERROR_CODE",
    "CircuitDefinitionInspection",
    "ExecutionPhase",
    "LaneName",
    "TaskAuditActionKind",
    "TaskExecutionMode",
    "TaskExecutionResult",
    "TaskResultHandle",
    "TaskSubmissionKind",
    "ValidationLevel",
    "ValidationNotice",
    "WorkerExecutionProvenance",
    "WorkerTaskName",
    "WorkerTaskRoute",
    "audit_action_for_phase",
    "build_task_crash_payload",
    "build_task_failure_payload",
    "build_task_start_payload",
    "build_task_success_payload",
    "build_worker_audit_summary",
    "extract_parameters_payload",
    "inspect_circuit_definition_source",
    "resolve_worker_task_route",
]
